### ISSUE TITLE
Time of Training

### ISSUE THREAD

**Issue by hadizand** [meyerscetbon/Deep-K-SVD#4]
How long does it take the model to be trained over CPU?

**Comment by Wisdoo11** [comment]
I tried to run the training script but it is very long on a GeForce RTX 2080 Ti (more than 100 hours for one epoch and three are required). Is it normal ?
If I understood the code correctly 400 * (321 - 127) * (481 -127) = 27,470,400 patches of size 128x128 are required for one epoch, am I right ?
Can we speed up the process by training only on a part of them ?

**Comment by meyerscetbon** [comment]
The generalization error will converge well before having seen the whole dataset, that's why it's not useful to train the network on all possible patches. In the training, the network considers as input, images of size 128 * 128 (or even 64 * 64), and after having some images of this size, the network will have reached its optimal generalization error.
